### PR TITLE
Reject clients without specifying "user" and "meta_token"

### LINKED ISSUE #1815: Login verification bugs when using fp-multiuser
**What version of frp are you using (./frpc -v or ./frps -v)?**
0.32.1

**What operating system and processor architecture are you using (`go env`)?**
linux_amd64
darwin_amd64

**Configures you used:**
frps:
``` [common]
bind_addr = 0.0.0.0
bind_port = 7100
bind_udp_port = 7001

log_level = trace
enable_prometheus = true
dashboard_addr = 0.0.0.0
dashboard_port = 7300

vhost_http_port = 8080

[plugin.multiuser]
addr = 127.0.0.1:7200
path = /handler
ops = Login
```
token:
```
frpc1=123
frpc2=abc 
```
frpc1
```
[common]
server_addr = x.x.x.x
server_port = 7100
user = frpc_worker1
meta_token = 123

admin_addr = 0.0.0.0
admin_port = 7400
admin_user = admin
admin_pwd = admin

[test_server]
type = stcp
local_ip = 127.0.0.1
local_port = 22
```
frpc2:
``` 
[common]
server_addr = x.x.x.x
server_port = 7100

[test_visitor]
type = stcp
role = visitor
server_name = test_server
bind_addr = 127.0.0.1
bind_port = 6000
```

**Steps to reproduce the issue:**
1. ./fp-multiuser -l 127.0.0.1:7200 -f ./tokens
2. Delete user and meta_token,but it can be successful sign in frps.

**Describe the results you expected:**
 login to server failed: invalid meta token

### PR DESCRIPTION
**Pull request by brvphoenix**
Fix https://github.com/fatedier/frp/issues/1815

### CODE REVIEW

File: pkg/server/controller/op.go [hunk 1]
```diff
@@ -34,7 +34,7 @@ func (c *OpController) HandleLogin(ctx *gin.Context) (interface{}, error) {
 
 	var res plugin.Response
 	token := content.Metas["token"]
-	if c.tokens[content.User] == token {
+	if (len(content.User) > 0 && len(token) > 0) && c.tokens[content.User] == token {
```
Comment (fatedier) [inline pkg/server/controller/op.go]: Can we give a more accurate error message for this like `user or meta token can not be empty`?

Comment (brvphoenix) [reply pkg/server/controller/op.go]: Done. Is this ok?

**Review by fatedier — APPROVED** [review]
